services:
  db:
    image: timescale/timescaledb:latest-pg17
    container_name: timescale-db
    environment:
      POSTGRES_DB: timescale_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d timescale_data"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: backend/TestTask.Api/Dockerfile
    container_name: testtask-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=timescale_data;Username=postgres;Password=postgres"
    ports:
      - "5029:8080"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: testtask-frontend
    depends_on:
      - api
    ports:
      - "4200:4200"

volumes:
  postgres_data: